### ISSUE TITLE
when package install in laravel  it gives error

### ISSUE THREAD

**Issue by lasamarndi** [CurrencyCloud/currencycloud-php#29] opened 2018-09-12 19:26 UTC

**Comment by steve-rhodes** [comment] 2018-09-13 20:00
It's because nobody is maintaining this package anymore. I ran into the same problem last year and my issues remained unanswered. I have no idea what's going on at currencycloud and how they can let this happen.

I even issued a pull request. Nobody looked at it...

The issue is the lack of addition for Symfony 4 in the package.json in order to play with Laravel.

**Comment by EAddario** [comment] 2018-11-26 10:00
Fixed in v1.0.1

**Closed as completed by EAddario** 2018-11-26 10:00 UTC
Labels: bug
